# (c) https://github.com/MontiCore/monticore
name: Test with various Versions
# As this project is our getting started document,
#  we test against a wider range of java & gradle versions

concurrency: # run this test workflow only once per "branch"
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: workflow_dispatch # only run this file on demand, as GitHub (to this day) does not support optional jobs

env:
  GRADLE_CLI_OPTS: "-Pci --build-cache --refresh-dependencies" # CLI options passed to Gradle
  GRADLE_BUILD_ACTION_CACHE_KEY_JOB: "test-cache-${{ github.head_ref }}.${{ github.sha }}"

permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11, 17, 21 ]
        gradle-version: [ '7.4.2', '7.6.4', '8.13', 'wrapper' ]
      fail-fast: false
    continue-on-error: true # just report incompatibility
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{matrix.java-version}}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{matrix.gradle-version}}
      - name: Gradle build
        run: gradle build ${{env.GRADLE_CLI_OPTS}}
